config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :articles_categories
  has_many :categories, through: :articles_categories

  validates :title, presence: true
  validates :body, presence: true

  def form_params
    {
      title: title,
      body: body,
      big_category: category_ids.include?(Category::BIG_ID) ? 1 : 0,
      middle_category: category_ids.include?(Category::MIDDLE_ID) ? 1 : 0,
      small_category: category_ids.include?(Category::SMALL_ID) ? 1 : 0
    }
  end
end

app/models/article_form.rb
class ArticleForm
  include ActiveModel::Model

  attr_accessor :title, :body, :big_category, :middle_category, :small_category
  attr_reader :article

  delegate :persisted?, to: :article

  validates :title, presence: true, article_length: { attribute: :body, minimum: 10 }
  validates :body, presence: true

  def initialize(article, attributes = {})
    @article = article
    super(attributes)
  end

  def big_category_label
    categories[Category::BIG_ID]
  end

  def middle_category_label
    categories[Category::MIDDLE_ID]
  end

  def small_category_label
    categories[Category::SMALL_ID]
  end

  def create
    return false if invalid?

    article.attributes = params
    CreateArticleAndSendMail.new(article).save
  end

  def update
    return false if invalid?

    article.update(params)
  end

  def params
    { title: title, body: body, category_ids: category_ids }
  end

  def category_ids
    ids = []
    ids << Category::BIG_ID if big_category == "1"
    ids << Category::MIDDLE_ID if middle_category == "1"
    ids << Category::SMALL_ID if small_category == "1"
    ids
  end

  private

    def categories
      @_categories ||= Category.article_checkboxes
    end
end

app/models/article_length_validator.rb
class ArticleLengthValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    validator = Validator.new(record, value, options)
    unless validator.valid?
      record.errors.add attribute.to_sym, "件名と本文で#{options[:minimum]}以上入力してください"
    end
  end

  class Validator
    def initialize(record, value, options)
      @record = record
      @value = value
      @options = options
    end

    def attribute
      @options[:attribute] || ""
    end

    def minimum
      @options[:minimum] || 0
    end

    def value
      @value || ""
    end

    def valid?
      length > minimum
    end

    def length
      sum = value.length
      sum += @record.send(attribute)&.length unless attribute.blank?
      sum
    end
  end
end

app/models/article_search_form.rb
class ArticleSearchForm
  include ActiveModel::Model

  attr_accessor :keyword
  attr_writer :from_date, :to_date

  validates :keyword, length: { maximum: 10 }, allow_nil: true
  validate :ensure_to_date_format, :ensure_from_date_format

  def articles
    query.articles
  end

  def from_date
    Date.parse(@from_date)
  rescue
    nil
  end

  def to_date
    Date.parse(@to_date)
  rescue
    nil
  end

  private

    def ensure_to_date_format
      ensure_date_format(:to_date, @to_date)
    end

    def ensure_from_date_format
      ensure_date_format(:from_date, @from_date)
    end

    def ensure_date_format(column, value)
      Date.parse(value) unless value.blank?
    rescue ArgumentError
      errors.add column, "日時の書式にあやまりがあります"
    end

    def query
      ArticleSearchQuery.new(keyword: keyword, from_date: from_date, to_date: to_date)
    end
end

app/models/article_search_query.rb
class ArticleSearchQuery
  include ActiveModel::Model

  attr_writer :keyword
  attr_accessor :from_date, :to_date

  def articles
    scope = Article.all
    scope = scope.where(conditions.join(" AND "), values) if conditions.count.nonzero?
    scope
  end

  def keyword
    "%#{Article.sanitize_sql_like(@keyword)}%" if @keyword
  end

  private

    def conditions
      result = []
      result << "title like :keyword" if keyword
      result << "created_at >= :from_date" if from_date
      result << "created_at <= :to_date" if to_date
      result
    end

    def values
      { from_date: from_date&.to_time, to_date: to_date&.to_time, keyword: keyword }
    end
end

app/models/articles_category.rb
class ArticlesCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles_categories
  has_many :articles, through: :articles_categories

  validates :name, presence: true, uniqueness: true

  BIG_ID = 1
  MIDDLE_ID = 2
  SMALL_ID = 3

  def self.article_checkboxes
    where(id: [BIG_ID, MIDDLE_ID, SMALL_ID]).inject({}) { |hash, record| hash[record.id] = record.name; hash }
  end
end

app/models/create_article_and_send_mail.rb
class CreateArticleAndSendMail
  include ActiveModel::Model
  define_model_callbacks :save, only: :after
  after_save :send_mail
  attr_reader :article

  def initialize(article)
    @article = article
  end

  def save
    run_callbacks :save do
      @article.save
    end
  end

  private

    def send_mail
      ArticleMailer.new_article(@article).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @article_search_form = ArticleSearchForm.new(article_search_form_params)
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article_form = ArticleForm.new(Article.new)
  end

  # GET /articles/1/edit
  def edit
    @article_form = ArticleForm.new(@article, @article.form_params)
  end

  # POST /articles
  def create
    @article_form = ArticleForm.new(Article.new, article_form_params)

    if @article_form.create
      redirect_to @article_form.article, notice: "Article was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    @article_form = ArticleForm.new(@article, article_form_params)

    if @article_form.update
      redirect_to @article_form.article, notice: "Article was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy!
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def article_form_params
      params.require(:article_form).permit(:title, :body, :big_category, :middle_category, :small_category)
    end

    def article_search_form_params
      params[:article_search_form]&.permit(:keyword, :to_date, :from_date)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: "Category was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy!
    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.haml
= form_for article_form, url: polymorphic_path(article_form.article) do |f|
  - if article_form.errors.any?
    #error_explanation
      %h2= "#{pluralize(article_form.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - article_form.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.check_box :big_category
    = f.label article_form.big_category_label
  .field
    = f.check_box :middle_category
    = f.label article_form.middle_category_label
  .field
    = f.check_box :small_category
    = f.label article_form.small_category_label
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form', article_form: @article_form

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 Listing articles

%search
  = form_for @article_search_form, url: articles_url, method: :get do |f|
    - if params.has_key?(:article_search_form) && @article_search_form.invalid?
      #error_explanation
        %h2= "#{pluralize(@article_search_form.errors.count, "error")} prohibited this article from being saved:"
        %ul
          - @article_search_form.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :keyword
      = f.text_field :keyword
    .field
      = f.label :from_date
      = f.date_field :from_date
    .field
      = f.label :to_date
      = f.date_field :to_date
    .actions
      = f.submit 'Search'

%table
  %thead
    %tr
      %th Title
      %th Body
      %th
      %th
      %th

  %tbody
    - @article_search_form.articles.each do |article|
      %tr
        %td= article.title
        %td= article.body
        %td= l article.created_at
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article

= render 'form', article_form: @article_form

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Body:
  = @article.body

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>